# prefixはt
set -g prefix C-t
# 再描画間隔は1秒
set-option -g status-interval 1
# 右下は日付
set-option -g status-right "#[fg=black][%Y/%m/%d]"
# ペインのサイズ変更を若干vim風に
bind -r < resize-pane -L 5
bind -r - resize-pane -D 5
bind -r + resize-pane -U 5
bind -r > resize-pane -R 5
